///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package com.elixr.microsoftbot;
//
//import org.junit.Test;
//
//@SpringbootTest
//class MicroSoftBotPrototypeApplicationTest {
//
//    @Test
//    void contextLoads() {
//    }
//
//}
