# This workflow will build and push a Java application to an Azure Web App when a commit is pushed to your default branch.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/en-us/azure/app-service/quickstart-java?tabs=javase&pivots=platform-linux
#
# To configure this workflow:
#
# 1. Download the Publish Profile for your Azure Web App. You can download this file from the Overview page of your Web App in the Azure Portal.
#    For more information: https://docs.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel#generate-deployment-credentials
#
# 2. Create a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE, paste the publish profile contents as the value of the secret.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 3. Change the value for the AZURE_WEBAPP_NAME. Optionally, change the JAVA_VERSION environment variable below.
#
# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more information on the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

name: Build and deploy War app to Azure Web App

env:
  AZURE_WEBAPP_NAME: MSBotPrototypeWebApp     # set this to the name of your Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"a472847e-2188-45df-a579-5f01e64e49dd","clientSecret":"55c4cbf8-3b2b-4c5d-85f5-c6dc63564bc8","subscriptionId":"76b05d92-0cbe-46b3-ac56-9bc9c8e85e80","tenantId":"4e260fd7-c2ff-4269-a326-31f8cc2b9673"}'
#          auth-type: IDENTITY
#          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
#          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

#    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK and Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MSBotPrototypeWebApp'
          publish-profile: 'in78Q~wFii6Wt4dbm-WpASSIy7v.92vD.~36JbOA'
          package: '*.war'

  deploy:
    permissions:
      contents: none
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MSBotPrototypeWebApp'
          slot-name: 'Production'
          publish-profile: 'in78Q~wFii6Wt4dbm-WpASSIy7v.92vD.~36JbOA'
          package: '*.war'
