name: Build and deploy War app to Azure Web App

env:
  AZURE_WEBAPP_NAME: MSBotPrototypeWebApp     # set this to the name of your Azure Web App
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - uses: actions/checkout@v3

      - name: Set up JDK and Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.war'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MSBotPrototypeWebApp'
          publish-profile: 'in78Q~wFii6Wt4dbm-WpASSIy7v.92vD.~36JbOA'
          package: '*.war'
